name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # 如果您的默认分支是 'master'，请改为 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2: 设置 Git 用户信息
      - name: Configure Git User
        run: |
          git config --global user.name "tydumpling"
          git config --global user.email "tydumpling@users.noreply.github.com"

      # 步骤 3: 安装必要的依赖（根据需要调整）
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根据您的项目需求调整 Node.js 版本

      - name: Install dependencies
        run: npm install

      # 步骤 4: 构建项目
      - name: Build project
        run: npm run build

      # 步骤 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
